### ISSUE TITLE
point cloud stream

### ISSUE THREAD

**Issue by Jaetriel** [lucasw/rviz_camera_stream#34]
Hey guys, is it possible to use this package to publish a sort of 'captured image' of a point cloud topic and publish those?

**Comment by flynneva** [comment]
@Jaetriel the recently published "rviz_animated_view_controller" does this sort of by publishing an image topic of the current rviz view if that's what you are looking for.

**Comment by lucasw** [comment]
If rviz can view it through the main window then rviz_camera_stream should capture it (and I imagine `rviz_animated_view_controller` is doing something similar with ogre and can do it too, but is limited to only the rviz main view?).

Because rviz_camera_stream can be attached to any tf frame with very different perspectives than the main view there can be strange view dependent artifacts- Markers or billboard rendering styles that align to the main rviz view will be seen at an angle here, and lighting will be funny because there is an rviz main view light source- but if point cloud points are set to render as points and aren't lit by that light it should be fine.  (There is an rviz plugin that allows creation of other light sources, I think attaching them to tf frames, I'd have to dig it up)
